### ISSUE TITLE
Need to be able to configure health check timeout

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#71] opened 2016-03-24 11:24 UTC
The health check timeout is 60s by default. We should be able to override this so we can deploy over slower networks.

**Comment by sabbyanandan** [comment] 2016-03-24 17:10
This is a duplicate of spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#70. The core functionality is now supported in `cf-java-client` (_see tracker stories_), we will have to have the mechanism to override the default timeout at the deployer level.

**Closed by sabbyanandan** 2016-03-24 17:10 UTC
Labels: enhancement
